[build]
command = "yarn build"
functions = "./netlify-functions"
publish = "public"
[build.environment]
NODE_VERSION = "15"
YARN_FLAGS = "--no-ignore-optional"
YARN_VERSION = "1.21.1"

[context.production.services]
git = "staging"
